version: "3.1"

services:
    tick_min:
        image: haifengat/tick_min
        container_name: tick_min
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - tick_csv_gz_path=/home/tick_csv_gz_path
            - min_csv_gz_path=/home/min_csv_gz_path
        volumes:
            - /mnt/future_csv_gz:/home/tick_csv_gz_path
            - /mnt/future_min_csv_gz:/home/min_csv_gz_path
            
